### ISSUE TITLE
Command names are becoming inconsistent

### ISSUE THREAD

**Issue by PeterJCLaw** [prophile/jacquard#54]
I added a couple of extra commands in #50, though I'm holding off suggesting that that be merged until we resolve the command naming issues it highlights. If we can't find a good solution soon-ish, it may be worth merging that ~now and fixing the names later, but I'm hoping that by discussing this now we can minimise the breakage needed.

Jacquard currently has the following commands:
- `list` (lists experiments)
- `list-users`
- `show $USER_ID` (shows the given user's settings)

#50 adds:
- `list --detailed` (which matches the current `list` behaviour, as #50 makes the default `list` output shorter)
- `show-experiment $EXPERIMENT_ID` (shows the same details as `list` currently does, but for a single experiment only)

This leaves us with inconsistency around what `list` and `show` operate on and they both end up with companion `list-users` & `show-experiment` commands which have the same issue in reverse.

I think we should move towards consistency sooner (while Jacquard is 0.x) so we don't end up with a UI as bad as `git` has.

There are a couple of ways I think we could go:

1. Replace the current commands with topic-based commands under new names:
    - `experiments`
    - `experiment $ID`
    - `users`
    - `user $ID`
    the advantages this has are:
    - (almost) completely new names minimise confusion
    - adding another class of thing can follow the same pattern without needing to become even more verbose
    A disadvantage is that this loses the imperative voice the commands currently all have. (I don't see this as a big deal since these commands are for display data only and make no changes to the system)

2. Adapt the current commands into unambiguous names:
    - `list-experiments`
    - `show-experiment $ID`
    - `list-users`
    - `show-user $ID`
    These feel quite verbose, though are much clearer and retain the imperative tone.
    There's a minor concern about users taking longer to remember that `show` is now `show-user` (the closer things are, the longer I expect users will take to adapt), though if we're going to break it anyway for a better command in the longer term this is probably doesn't matter too much.

There's also a debate to be had about whether the other (non-conflicting) commands such as `launch`, `override` etc. should be disambiguated in a similar manner (to be `launch-experiment` etc.).

**Comment by prophile** [comment]
I'd float a third structure here which is to add an additional level of subcommand hierarchy:

* `experiment` (for the list)
* `experiment show`
* `experiment launch`
* `experiment conclude`
* `user` (for the list)
* `user show`

Prior art here is the [iproute2][iproute2] suite which segments its subcommands as [subject-class] [verb]. For instance, `ip link show` or `ip addr add 2001::bee5/16 dev eth0`.

[iproute2]: https://wiki.linuxfoundation.org/networking/iproute2

**Comment by PeterJCLaw** [comment]
Sounds good, though I'd be in favour of the addition of explicit `list` commands for both listings (even if it's the default).

**Comment by PeterJCLaw** [comment]
I'm planning to implement this shortly. Do you think it's worth keeping the old names for now, or should we go ahead and just break things?

I'm most tempted to do the latter as it is easier and will force people to learn the new commands faster.

Either way, I'd appreciate it if we could hold off adding any further commands until it's landed.

**Comment by PeterJCLaw** [comment]
At the moment external packages can contribute commands via the `jacquard.commands` entry points list. Do we feel it's important to allow the contribution of subcommands in a similar manner, or can we ignore that for now?

**Comment by PeterJCLaw** [comment]
I think I've found a way of supporting sub-subcommand contribution by just allowing spaces in the entry point names (which appears to work) and then splitting them before adding to the subcommand parsers.

I've put some initial renaming work in https://github.com/PeterJCLaw/jacquard/tree/rename-commands, though no spaces support yet.

**Comment by prophile** [comment]
Also looked at a `subject-verb-object` structure:

* `jacquard list experiments`
* `jacquard show experiment <id>`
* `jacquard list users`
* `jacquard show user <id>`
* `jacquard show defaults`

It's similar to the REPL structure from `gdb`.

Advantages:

* Reads very naturally (Jacquard, show <this thing>);
* Subject-verb-object natural word order for English speakers,
* Object qualifiers appear next to the object (confer e.g. `jacquard user show 5`, where `user 5` is split across the verb);

Disadvantages:

* Consistency issues in not always qualifying with object types, compare `jacquard show experiment cta_in_green` but `jacquard launch cta_in_green`.
* Verbs in the middle makes it harder to edit previous commands on the command line, a problem it shares with `systemctl`. For instance, if one wants to show an experiment then stop it, one has to jump to the middle of the line to edit `show experiment` to `conclude`.

**Comment by PeterJCLaw** [comment]
We've now moved to the `subject-verb-object` structure proposed by @prophile in his latest comment, I think this is done.
