### ISSUE TITLE
Anonymous user gets included in partial rollouts

### ISSUE THREAD

**Issue by PeterJCLaw** [prophile/jacquard#96]
I recently enabled an internal rollout using a command like `jacquard rollout --percent 100 --with-tag internal-users`, however the anonymous user was included in this.

I don't believe that anonymous users appear in our directories, so I suspect that this relates to the way that tags are tested against users not in directories when a rollout happens.

**Comment by prophile** [comment]
c9955eadfb2c1807b6da6cd5d3a82c784a88fa32
